---
:gallery:
  - :file: mirror.jpg
    :movie: Mirror Mirror
  - :file: mirror2.jpg
    :movie: Mirror Mirror
  - :file: spivet_transformation.jpg
    :movie: The Young and Prodigious Spivet
  - :file: zero.jpg
    :movie: Zero Hour
    :who: Michael Nyqvist
    :credit: Photo by Phillippe Bosse – © 2012 American Broadcasting Companies, Inc.
  - :file: wb.jpg
    :movie: Warm Bodies
    :who: Analeigh Tipton
    :credit: Photo by Jan Thijs‚ © 2012 Summit Entertainment, LLC.
  - :file: wb2.jpg
    :movie: Warm Bodies
  - :file: wb_transformation.jpg
    :movie: Warm Bodies
  - :file: spivet_tattoo.jpg
    :movie: The Young and Prodigious Spivet
  - :file: road.jpg
    :movie: On the Road
  - :file: kabuki.jpg
    :movie: Beastly
  - :file: kabuki2.jpg
    :movie: Beastly
  - :file: timekeeper.jpg
    :movie: The Timekeeper
  - :file: timekeeper2.jpg
    :movie: The Timekeeper
  - :file: timekeeper3.jpg
    :movie: The Timekeeper
  - :file: durham.jpg
    :movie: Durham County
  - :file: durham2.jpg
    :movie: Durham County
:movies:
  Warm Bodies: tt1588173
  The Young and Prodigious Spivet: tt1981107
  Beastly: tt1152398
  Zero Hour: tt2215797
  The Timekeeper: tt1087872
  Mirror Mirror: tt1667353
  On the Road: tt0337692
  Durham County: tt0885761
